### PR TITLE
Change encoding to utf-8

### PR DESCRIPTION
**Pull request by KuoE0**
I think all files should be UTF-8 to make it more compatible with other system.

### CODE REVIEW

**Comment by wengan-li** [comment]
Interesting.....
It should already UTF-8 because I wrote it in gedit with default encoding.

I think the git said you changed the line, maybe is because of end-line symbol is Windows (\r\n) not *nix (\n) style.
But yes, I still prefer *nix style and UTF-8.

My development platform is Win 7+ gedit +Texmaker (in VM) and CentOS 7 + Git Cola (Host).
So I don't know which side causing this problem.
But I think the gedit is changed my expected that it may not using *nix style and UTF-8.

Honestly, I really don't feel any difference.
Or it really don't have any problem.

But still I believe in you and git.

**Comment by KuoE0** [comment]
Thank you! And I'm sorry that I forgot to mention I also changed it to *nix style. About the encoding, I opened the file and saw the garbled text. So I think the encoding should not be UTF-8.

**Comment by wengan-li** [comment]
Interesting.....
What is your platform and text editor to open that file ?
And the file is store in local, cloud, or NAS ?

**Comment by KuoE0** [comment]
OS: OS X 10.10
Editor: TeXShop 3.62 (MacTeX)

I just cloned the repo to my local file system.

**Comment by wengan-li** [comment]
I haven't try TeXShop before, so I am not sure it is default with UTF-8.

I am thinking about this discussion, maybe adding one more line will guarantee the encoding is correct.
http://tex.stackexchange.com/questions/281826/which-encoding-should-i-use-with-texshop-on-a-mac
But this also tell me that the TexShop may not be using UTF-8 if you don't set it in preferences.

But I don't know is this means all files also needed to add this line or just a signal file.
Maybe you can try it if you get the times.

**Pull request merged**
