### PR TITLE
add funciton for DOI

### PR DESCRIPTION
**Pull request by ChampDBG**
According to NCKU Library, students have to add doi number in their thesis. 
Therefore, I make this function. User can fill in their doi number in ncku.tex.

reference:
http://etds.lib.ncku.edu.tw/files/2012050003.pdf

### CODE REVIEW

**Comment by wengan-li** [comment]
Hi,

I am really really sorry that missed the notification email.
Very busy on my work.

Ready thank you for your update.
Let me test it and will merge this week.

Thank you and sorry for late process.

**Comment by wengan-li** [comment]
Sorry,

I just having Issue #39,
I still can't able to check the code yet.

**Comment by wengan-li** [comment]
@ChampDBG 
Wonderful !
Thank you very much, help this could help for more schoolmate.

**Comment by ChampDBG** [comment]
@wengan-li,
Thanks for your checking.
It is nice that you move this function to the appropriate file.

**Pull request merged**
